export const ROTOR_I_WIRING = "EKMFLGDQVZNTOWYHXUSPAIBRCJ";
export const ROTOR_I_NOTCH = 'Q';

export const ROTOR_II_WIRING = "AJDKSIRUXBLHWTMCQGZNPYFVOE";
export const ROTOR_II_NOTCH = 'E';

export const ROTOR_III_WIRING = "BDFHJLCPRTXVZNYEIWGAKMUSQO";
export const ROTOR_III_NOTCH = 'V';

export const REFLECTOR_B_WIRING = "YRUHQSLDPXNGOKMIEBFZCWVJAT";
